name: volga
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  splashscreen: ^2.0.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/Heart.png
      - assets/images/звездочки.png
      - assets/images/круг_побольше.png
      - assets/images/круг_поменьше.png
      - assets/images/menu.png
      - assets/images/heart_1.svg
      - assets/images/heart_2.jpg